1

   Abaqus 2024                                  Date 09-May-2026   Time 13:30:09
   For use by Supplied by Team-SolidSQUAD under license from Dassault Systemes or its subsidiary.

 Stage 4B: Cycle-19 to Cycle-20 Exact-State Injection (STATEV-only)              
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        A N A L Y S I S    D A T A C H E C K




                        S T E P       1     S T A T I C   A N A L Y S I S


                                                                                          

     AUTOMATIC TIME CONTROL WITH -
          A SUGGESTED INITIAL TIME INCREMENT OF                1.000E-03
          AND A TOTAL TIME PERIOD OF                            1.00    
          THE MINIMUM TIME INCREMENT ALLOWED IS                1.000E-08
          THE MAXIMUM TIME INCREMENT ALLOWED IS                2.000E-02

     LINEAR EQUATION SOLVER TYPE         DIRECT SPARSE

     COLLECTING MODEL CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS

     COLLECTING STEP CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS



     JOB TIME SUMMARY
       USER TIME (SEC)      =      0.0    
       SYSTEM TIME (SEC)    =      0.0    
       TOTAL CPU TIME (SEC) =      0.0    
       WALLCLOCK TIME (SEC) =            0
       MEMORY PEAK (GB)     =            0
